# Generated by Django 6.0.2 on 2026-02-23 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('date', models.DateField(verbose_name='data')),
                ('payment_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('BOLETO', 'Boleto'), ('PIX', 'Pix')], default='PIX', max_length=10, verbose_name='tipo de pagamento')),
                ('is_installment', models.BooleanField(default=False, verbose_name='é parcelada')),
                ('installment_current', models.PositiveIntegerField(blank=True, null=True, verbose_name='parcela atual')),
                ('installment_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='total de parcelas')),
                ('installment_group_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='grupo de parcelas')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='é recorrente')),
                ('from_paycheck', models.BooleanField(default=False, verbose_name='do contracheque')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='banks.bank', verbose_name='banco')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
