# Generated by Django 6.0.2 on 2026-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CASH', 'Saque/Dinheiro')], default='PIX', max_length=10, verbose_name='tipo de pagamento'),
        ),
    ]
