# Generated by Django 6.0.2 on 2026-03-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_change_payment_type_to_fk'),
        ('financial_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financial_calendar.creditcard', verbose_name='cartão de crédito'),
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_month',
            field=models.DateField(blank=True, db_index=True, help_text='Primeiro dia do mês financeiro (calculado automaticamente)', null=True, verbose_name='mês financeiro'),
        ),
    ]
