# Generated by Django 6.0.2 on 2026-03-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_populate_financial_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='boleto_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('paid', 'Pago')], help_text='Status do boleto (somente para despesas tipo boleto)', max_length=10, null=True, verbose_name='status do boleto'),
        ),
        migrations.AddField(
            model_name='expense',
            name='due_day',
            field=models.PositiveIntegerField(blank=True, help_text='Dia do mês em que o boleto vence (1-31)', null=True, verbose_name='dia de vencimento'),
        ),
    ]
