# Generated by Django 6.0.2 on 2026-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_bank_expense_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurrence_ends_at',
            field=models.DateField(blank=True, db_index=True, help_text='Mês financeiro (1º dia) a partir do qual esta recorrente para de ser gerada', null=True, verbose_name='recorrência termina em'),
        ),
    ]
