# Generated by Django 6.0.2 on 2026-03-21 15:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='limite')),
                ('month', models.DateField(help_text='Primeiro dia do mês (ex: 2026-03-01)', verbose_name='mês de referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Se vazio, aplica ao total de despesas do mês.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='categories.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['-month', 'name'],
            },
        ),
    ]
