# Generated by Django 6.0.2 on 2026-03-21 14:36

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('padrao', models.IntegerField(default=38, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(45)])),
                ('gdae_perc', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Percentual GDAE (40–100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('40')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('has_aeq', models.BooleanField(default=False)),
                ('aeq_perc', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual AEQ (0–30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))])),
                ('vpi', models.DecimalField(decimal_places=2, default=Decimal('84.08'), max_digits=10)),
                ('has_funpresp', models.BooleanField(default=False)),
                ('funpresp_perc', models.DecimalField(decimal_places=2, default=Decimal('8.50'), help_text='Percentual Funpresp (7.5–8.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('7.5')), django.core.validators.MaxValueValidator(Decimal('8.5'))])),
                ('funcao_comissionada', models.CharField(blank=True, choices=[('', 'Nenhuma'), ('FC-1', 'FC-1'), ('FC-2', 'FC-2'), ('FC-3', 'FC-3'), ('FC-4', 'FC-4'), ('FC-5', 'FC-5'), ('FC-6', 'FC-6'), ('FC-7', 'FC-7')], default='', max_length=4)),
                ('has_creche', models.BooleanField(default=False)),
                ('num_filhos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dependentes_ir', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_2026', models.BooleanField(default=True)),
                ('approved_2027', models.BooleanField(default=False)),
                ('approved_2028', models.BooleanField(default=False)),
                ('approved_2029', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Salarial',
                'verbose_name_plural': 'Configurações Salariais',
            },
        ),
        migrations.CreateModel(
            name='SalarySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Mês de referência (primeiro dia do mês)')),
                ('padrao', models.IntegerField()),
                ('effective_year', models.IntegerField(help_text='Ano efetivo usado para as tabelas')),
                ('vb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gdae', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aeq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vpi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('auxilio_alimentacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auxilio_creche', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bruto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('abate_teto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funpresp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('irpf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot Salarial',
                'verbose_name_plural': 'Snapshots Salariais',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('month',), name='unique_salary_month')],
            },
        ),
    ]
