# Generated by Django 6.0.2 on 2026-03-22 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='ícone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de pagamento',
                'verbose_name_plural': 'tipos de pagamento',
                'ordering': ['name'],
            },
        ),
    ]
