# Generated by Django 6.0.2 on 2026-03-22 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='ícone')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria de receita',
                'verbose_name_plural': 'categorias de receita',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('date', models.DateField(verbose_name='data')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='é recorrente')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='banks.bank', verbose_name='banco')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='incomes.incomecategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
