# Generated by Django 6.0.2 on 2026-03-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_create_income_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='financial_month',
            field=models.DateField(blank=True, db_index=True, help_text='Primeiro dia do mês financeiro (calculado automaticamente)', null=True, verbose_name='mês financeiro'),
        ),
    ]
