# Generated by Django 6.0.2 on 2026-03-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_add_financial_month_to_income'),
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='bank',
        ),
        migrations.AddField(
            model_name='income',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='third_parties.thirdparty', verbose_name='terceiro'),
        ),
    ]
