# Generated by Django 6.0.2 on 2026-04-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_calendar', '0002_alter_creditcard_closing_day_and_more'),
        ('incomes', '0003_remove_income_bank_income_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_incomes', to='financial_calendar.creditcard', verbose_name='cartão de crédito (devolução)'),
        ),
    ]
